<x-app-layout>

   <style>

  
        /* overflow: hidden;
  position: relative; */
/* 
  @media print {
        font-size: 14px;

        @page {size: A4 landscape; }

    /* .row.no-gutter {
  margin-left: 0;
  margin-right: 0;
} */
/* .row.no-gutter [class*='col-']:not(:first-child),
.row.no-gutter [class*='col-']:not(:last-child) {
  padding-right: 0;
  padding-left: 0;
} */
/* .row > div {
  background: rgb(250, 250, 250);
  border: 0.5px solid;
} */

      /* } */ 

      @media print {

@page {
    size: landscape letter;
    border: red;
   
 }
 body{
    font-size: 13px;
    -webkit-print-color-adjust: exact !important;

   
 }


}
.row  {
   
   /* outline:1px solid #ccc; */
 
}


   </style>


    


    <div class="container-fluid d-flex flex-column bg-white">
        <div class="row">

         <div class="col">

            <div class="row">
                <div class="col">
                   @php
                       




                   @endphp 
                </div>
            </div>

         </div>

            <div class="col text-center">

                @foreach ($school as $school_item)
    
                <img src="{{$school_item->school_logo}}" height="180px" width="180px" class="img-fluid img-rounded  rounded mx-auto d-block" alt="">
            

               <h2 class="text-center font-weight-bold ">{{$school_item->school_name}}</h2>
                @endforeach

                <hr>
                @foreach ($student_details as $student_details_item)
                 
                @if ($student_details_item->stream_name=="Grade 1" OR $student_details_item->stream_name=="Grade 2")
                <h2 class=" text-center font-weight-bold ">Foundation Phase</h2>
                @endif
                @if ($student_details_item->stream_name=="Grade 3" OR $student_details_item->stream_name=="Grade 4")
                <h1 class="display-5 text-center font-weight-bold ">Middle Phase</h1>
        
             @endif
             @if ($student_details_item->stream_name=="Grade 5")
             <h1 class="display-5 text-center font-weight-bold ">Upper Phase</h1>
          @endif
          <div class="pic mx-auto" style=" width:120px; height:120px; border-radius:50%; background-image: url({{$student_details_item->student_image}}); background-position: center; background-size:100% auto; background-repeat: no-repeat;"></div>
          <p class="text-justify">
            <h5 class=" ">Student Name: <strong>{{$student_details_item->lastname}} {{$student_details_item->name}} {{$student_details_item->middlename}}</strong></h3>
            <h5 class="  ">Personal Identification Number: <strong>{{$student_details_item->pin}} </strong></h5>
            <h5 class=" ">Class: <strong>{{$student_details_item->grade_name}} Report </strong></h5>

            @foreach ($academic_sessions as $session)
            <h5 class="">Reporting Period: <strong>{{$session->term_name}} {{$session->academic_year}} </strong></h5>   
            @endforeach
          
          </p>
          <hr>
          <small class="text-justify">&copy {{date('Y')}} CBE Report generated by the Shunifu Platform. Shunifu is Eswatini's leading school management platform, developed through the incubatory support of the Royal Science & Technology Park (RSTP). <br>7689 0726 +268 517 9400</small>
          
                @endforeach
    
           

              
    
            </div>



        </div>
        
  
    
       </div>
      




   

 
</x-app-layout>